# 配置文件请严格遵循yaml语法格式，yaml学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# 定时时间
alarm_timed: '20:38'

# 格言渠道
# 1 : ONE●一个
# 2 : 词霸（每日英语，双语）
# 3 : 土味情话（失效中）
# 4 : 一言
dictum_channel: 3

girlfriend_infos:
  -
    #女友微信昵称或者备注名，不能输入微信号。
    wechat_name: 'Alina-乖乖'
    #女友所在桂林
    city_name: '咸阳'
    # 从那天开始勾搭的（可空）
    start_date: '2015-04-05'
    # 短句的最后留言（可空）
    sweet_words: '来自alan。'

  #如果你有多个人需要发送，则参照这个样式，复制即可
  #如不需要，则删除或注解下面所有的数据
 